version: '2'
services:
  opentraffic-reporter:
    image: opentraffic/reporter:latest
    container_name: opentraffic-reporter
    ports:
      - "8002:8002"
    volumes:
      - ~/volumes/opentraffic/reporter/data/valhalla:/data/valhalla
    environment:
      REPORT_LEVELS: "0,1"
      TRANSITION_LEVELS: "0,1"
#      THRESHOLD_SEC: 15
      TODO_DATASTORE_URL: "http://opentraffic-datastore:8003/store?"
      MATCHER_LISTEN_PORT: 8002
    restart: unless-stopped

  opentraffic-reporter-kafka:
    image: opentraffic/reporter:latest
    container_name: opentraffic-reporter-kafka
    volumes:
      - ~/volumes/opentraffic/reporter-kafka/results:/results
    environment:
      - FORMATTER=",sv,\|,1,9,10,0,5,yyyy-MM-dd HH:mm:ss"
      - DATAPATH=/data/valhalla
    command:
      bash -c "echo \"Formatting with $${FORMATTER}\" && sleep 30 && /usr/local/bin/reporter-kafka --bootstrap opentraffic-kafka:9092 --topics raw,formatted,batched --formatter \"$${FORMATTER}\" --reporter-url http://opentraffic-reporter:8002/report? --privacy 1 --quantisation 3600 --flush-interval 15 --source NTEST --output-location /results"
    depends_on:
      - opentraffic-kafka
    restart: unless-stopped

  opentraffic-zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: opentraffic-zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  opentraffic-kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: opentraffic-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: opentraffic-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: opentraffic-zookeeper:2181
      KAFKA_CREATE_TOPICS: "raw:4:1,formatted:4:1,batched:4:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - opentraffic-zookeeper
    restart: unless-stopped

networks:
  default:
    external:
      name: docker_default
