# Common configuration shared between all applications
configserver:
    name: Local Rahpey Registry
    status: Connected to the Rahpey Dev Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8761/eureka/
