version: '2'

services:
  nginx:
    build: .
    container_name: rahpey-nginx-http-only
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/www:/home/www
