#common configuration shared between all applications
configserver:
    name: Rahpey Docker JHipster Registry
    status: Connected to the Rahpey JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: fdefa384698d04ad3508109cfbf3455666643193
    logging:
        logstash: # forward logs to ELK
            enabled: false
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
spring:
    zipkin:
        baseUrl: http://localhost:9411
        enabled: false

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
