version: '2'

services:
  graphhopper:
    build: .
    container_name: rahpey-graphhopper-dev
    ports:
      - 8989:8989
    volumes:
      - ~/osm:/data
    environment:
      OSM_FILE: /data/import.osm.pbf
    logging:
      driver: json-file
      options:
        max-size: '10k'
        max-file: '3'
