version: '2'
services:
    jhipster-elasticsearch:
        image: jhipster/jhipster-elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: 68719476736
                hard: 68719476736
        volumes:
            - ./log-data:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xmx512m -Xms512m
            - ES_HEAP_SIZE=1g
        mem_limit: 1g
    jhipster-logstash:
        image: jhipster/jhipster-logstash
        command: logstash -f /conf/logstash.conf
        ports:
            - 5000:5000/udp
        volumes:
            - ./log-conf/:/conf
    jhipster-console:
        image: jhipster/jhipster-console
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        # Uncomment this section to have kibana JSON files loaded from a volume
        #volumes:
        #    - ./dashboards:/tmp/dashboards
    jhipster-alerter:
        image: jhipster/jhipster-alerter
        volumes:
            - ./alerts/rules/:/opt/elastalert/rules/
            - ./alerts/config.yaml:/opt/elastalert/config.yaml
