version: '2'
services:
  #=============================================================================
  # Nginx
  #=============================================================================
  nginx:
    extends:
      file: ../nginx-http/docker-compose.yml
      service: nginx
    restart: unless-stopped
  #=============================================================================
  # Graphhopper (route engine)
  #=============================================================================
  graphhopper:
    container_name: rahpey-graphhopper
    extends:
      file: ../graphhopper/docker-compose.yml
      service: graphhopper
    restart: unless-stopped
  #=============================================================================
  # OSRM (a converter service for convert Graphhopper response to OSRM)
  #=============================================================================
  osrm:
    container_name: rahpey-osrm
    extends:
      file: ../osrm/docker-compose.yml
      service: osrm
    restart: unless-stopped
  #=============================================================================
  # OpenTileServer (tile server)
  #=============================================================================
  opentileserver:
    container_name: rahpey-opentileserver
    extends:
      file: ../opentileserver/docker-compose.yml
      service: opentileserver
    restart: unless-stopped
  #=============================================================================
  # JHipster registry
  #=============================================================================
  jhipster-registry:
    container_name: rahpey-registry
    extends:
      file: ../registry/jhipster-registry.yml
      service: jhipster-registry
    environment:
      - JAVA_OPTS=-Xmx768m -Xms256m
      - _JAVA_OPTIONS=-Xmx768m -Xms256m
    restart: unless-stopped
  #=============================================================================
  # UAA server
  #============================================================================
  rahpey-uaa:
    image: rahpey_uaa
    container_name: rahpey-uaa
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-postgres-uaa:5432/uaa
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx1024m -Xms256m
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
    depends_on:
      - rahpey-postgres-uaa
      - jhipster-registry
    restart: unless-stopped
  rahpey-postgres-uaa:
    image: postgres:9.6.2
    container_name: rahpey-postgres-uaa
    volumes:
      - ~/volumes/uaa/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=uaa
      - POSTGRES_PASSWORD=
    restart: unless-stopped
  #=============================================================================
  # Route service
  #=============================================================================
  rahpey-route:
    image: rahpey_route
    container_name: rahpey-route
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-postgres-route:5432/route
      - JHIPSTER_SLEEP=90 # gives time for UAA and the database to boot
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx1024m -Xms256m
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
    depends_on:
      - rahpey-postgres-route
      - jhipster-registry
      - rahpey-uaa
      - graphhopper
    restart: unless-stopped
  rahpey-postgres-route:
    image: postgres:9.6.2
    container_name: rahpey-postgres-route
    volumes:
      - ~/volumes/route/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=route
      - POSTGRES_PASSWORD=
    restart: unless-stopped
  #=============================================================================
  # Traffic service
  #=============================================================================
  rahpey-traffic:
    image: rahpey_traffic
    container_name: rahpey-traffic
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-postgres-traffic:5432/traffic
      - JHIPSTER_SLEEP=90 # gives time for UAA and the database to boot
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx1024m -Xms256m
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
    depends_on:
      - rahpey-postgres-traffic
      - jhipster-registry
      - rahpey-uaa
    restart: unless-stopped
  rahpey-postgres-traffic:
    image: postgres:9.6.2
    container_name: rahpey-postgres-traffic
    volumes:
      - ~/volumes/traffic/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=traffic
      - POSTGRES_PASSWORD=
    restart: unless-stopped
  #=============================================================================
  # Gateway
  #=============================================================================
  rahpey-gateway:
    image: rahpey_gateway
    container_name: rahpey-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-postgres-gateway:5432/gateway
      - JHIPSTER_SLEEP=90 # gives time for uaa and the database to boot
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx1024m -Xms256m
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
    ports:
      - 8080:8080
    depends_on:
      - rahpey-postgres-gateway
      - jhipster-registry
      - rahpey-uaa
    restart: unless-stopped
  rahpey-postgres-gateway:
    image: postgres:9.6.2
    container_name: rahpey-postgres-gateway
    volumes:
      - ~/volumes/gateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
    restart: unless-stopped
