version: '2'
services:
  #=============================================================================
  # Nginx
  #=============================================================================
  nginx:
    image: nginx:alpine
    container_name: rahpey-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/www:/home/www
    restart: unless-stopped
  #=============================================================================
  # Graphhopper (route engine)
  #=============================================================================
  graphhopper:
    container_name: rahpey-graphhopper
    extends:
      file: ../graphhopper/docker-compose.yml
      service: graphhopper
    restart: unless-stopped
  #=============================================================================
  # OpenTileServer (tile server)
  #=============================================================================
  opentileserver:
    container_name: rahpey-opentileserver
    extends:
      file: ../opentileserver/docker-compose.yml
      service: opentileserver
    restart: unless-stopped
  #=============================================================================
  # JHipster registry
  #=============================================================================
  jhipster-registry:
    container_name: rahpey-registry
    extends:
      file: ../registry/jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
      - JAVA_OPTS=-Xmx768m -Xms256m
      - _JAVA_OPTIONS=-Xmx768m -Xms256m
    restart: unless-stopped
  #=============================================================================
  # UAA server
  #============================================================================
  rahpey-uaa:
    image: rahpey_uaa
    container_name: rahpey-uaa
    external_links:
      - rahpey-uaa-postgresql:postgresql
      - jhipster-registry:jhipster-registry
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-uaa-postgresql:5432/uaa
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
      - JAVA_OPTS=-Xmx768m -Xms256m
      - _JAVA_OPTIONS=-Xmx768m -Xms256m
    depends_on:
      - rahpey-uaa-postgresql
      - jhipster-registry
    restart: unless-stopped
  rahpey-uaa-postgresql:
    container_name: rahpey-uaa-postgresql
    extends:
      file: postgresql/postgresql.yml
      service: postgresql
    environment:
      - POSTGRES_USER=uaa
      - POSTGRES_PASSWORD=
    restart: unless-stopped
  #=============================================================================
  # Route service
  #=============================================================================
  rahpey-route:
    image: rahpey_route
    container_name: rahpey-route
    external_links:
      - rahpey-route-postgresql:postgresql
      - jhipster-registry:jhipster-registry
      - graphhopper:graphhopper
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-route-postgresql:5432/route
      - JHIPSTER_SLEEP=60 # gives time for UAA and the database to start and execute the migration scripts
#     - JAVA_OPTS=-Xmx2048m -Xms256m
#     - _JAVA_OPTIONS=-Xmx2048m -Xms256m
    depends_on:
      - rahpey-route-postgresql
      - jhipster-registry
      - rahpey-uaa
    restart: unless-stopped
  rahpey-route-postgresql:
    container_name: rahpey-route-postgresql
    extends:
      file: postgresql/postgresql.yml
      service: postgresql
    environment:
      - POSTGRES_USER=route
      - POSTGRES_PASSWORD=
    restart: unless-stopped
  #=============================================================================
  # Gateway
  #=============================================================================
  rahpey-gateway:
    image: rahpey_gateway
    container_name: rahpey-gateway
    external_links:
      - rahpey-gateway-postgresql:postgresql
      - jhipster-registry:jhipster-registry
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rahpey-gateway-postgresql:5432/gateway
      - JHIPSTER_SLEEP=60 # gives time for uaa and the database to start and execute the migration scripts
      - JAVA_OPTS=-Xmx1024m -Xms256m
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
    ports:
      - 8080:8080
    depends_on:
      - rahpey-gateway-postgresql
      - jhipster-registry
      - rahpey-uaa
      - rahpey-route
    restart: unless-stopped
  rahpey-gateway-postgresql:
    container_name: rahpey-gateway-postgresql
    extends:
      file: postgresql/postgresql.yml
      service: postgresql
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
    restart: unless-stopped
