export let GATEWAY_HOST_NAME = 'navio.biz';
export let GATEWAY_HTTP = 'http://' + GATEWAY_HOST_NAME;
export let GATEWAY_HTTPS = 'https://' + GATEWAY_HOST_NAME;
export let AUTH_API_BASE_URL = GATEWAY_HTTPS + '/uaa';
// export let ROUTE_API_BASE_URL = GATEWAY_HTTPS + '/route/v1';
export let ROUTE_API_BASE_URL = 'https://graphhopper.com/api/1/route';
export let ROUTE_API_KEY = 'ae9e6f11-30e8-4842-8036-a9b12f85e2d8';
export let TRAFFIC_API_BASE_URL = GATEWAY_HTTPS + '/traffic/v1'
// export let TILE_API_BASE_URL = GATEWAY_HTTP + '/tile';
export let TILE_API_BASE_URL = 'http://tile.openstreetmap.org/';
export let OVERPASS_API_BASE_URL = 'http://overpass-api.de/api/';
// export let GEOCODING_API_BASE_URL = GATEWAY_HTTP + '/geocoding/';
export let GEOCODING_API_BASE_URL = 'http://nominatim.openstreetmap.org/';